title = 'ECG Project Config'

[general]
r_seed = 1776
np_r_seed = 1777

[model]
#model proper
input_size = 12
hidden_size = 64
num_layers = 1
num_classes = 5	#for diagnostic superclass classification
num_workers = 0
batch_size = 10	#this is about max for cc_1. cc_2 can go higher
initial_learn_rate = 0.001

#training proper
epochs = 100
validation_patience = 50		#how many validation chances training has to get better
validation_frequency = 5		#how often we validate in batches
lr_scheduler = false
step_size = 10
gamma = 0.5


#200 all is good for serious testing
#10, 5, 5 is good for rapid testing

#data proper
test_fold = 10
validation_fold = 9


[data]
path = 'D:/ECG_Data/'
timesteps = 10
features = 10
sampling_rate = 100   #100 or 500
num_leads = 12
train_index = 27
train_key = 'diagnostic_superclass'

[meta]
output_csv = true	#TOML booleans are lower case
csv_name = 'results_'	#don't include the '.csv' suffix
validation = true
monitor_gpu = true