title = "ECG Project Config"

[model]
input_size = 12
hidden_size = 100
num_layers = 2
num_classes = 2

[training]
batch_size = 12
epochs = 100
initial_learn_rate = 0.001

[data]
path = "D:/ECG_Data/"
timesteps = 10
features = 10
sampling_rate = 100   #100 or 500

